services:
  bot:
    container_name: bot
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: sh -c "alembic upgrade head && python cli.py"
    volumes:
      - ./src:/bot/code
    depends_on:
      - db

  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=vento
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vento
    volumes:
      - vento_db:/var/lib/postgresql/data
    ports:
      - "5433:5432"

  redis:
    image: redis:7-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "8202:6379"
    volumes:
      - redis_data:/data

volumes:
  vento_db:
  redis_data:
