version: "3.9"

services:
  db:
    image: postgres:17-alpine
    environment:
      - POSTGRES_USER=vento
      - POSTGRES_PASSWORD=password
      - POSTGRES_DB=vento
    volumes:
      - vento_db:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U vento -d vento"]
      interval: 5s
      timeout: 3s
      retries: 12
    restart: unless-stopped
    networks: [internal]
    ports:
      - "127.0.0.1:5432:5432"

  redis:
    image: redis:7-alpine
    restart: always
    healthcheck:
      test: [ "CMD", "redis-cli", "ping" ]
      interval: 1s
      timeout: 3s
      retries: 30
    ports:
      - "8202:6379"
    volumes:
      - redis_data:/data
    networks: [internal]

  bot:
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - .env
    command: sh -c "alembic upgrade head && python cli.py"
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_healthy
    restart: unless-stopped
    expose:
      - "8080"
    networks: [internal]

  caddy:
    image: caddy:2-alpine
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile:ro
      - caddy_data:/data
      - caddy_config:/config
    networks: [internal]

volumes:
  vento_db:
  caddy_data:
  caddy_config:
  redis_data:

networks:
  internal:
    driver: bridge
