name: Deploy to production

on:
  push:
    branches: [production]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: SSH deploy
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_KEY }}
          port: ${{ secrets.SSH_PORT }}
          command_timeout: 30m
          script: |
            set -e
            cd /opt/vento-bot
            git fetch --all
            git checkout production
            git pull --ff-only
            docker compose -f docker-compose.prod.yml --env-file .env build
            docker compose -f docker-compose.prod.yml --env-file .env up -d
            docker image prune -f